import { SellerOnboarding } from './seller-account';
import { BuyerOrderBoard, EscrowGuarantee } from './escrow';
import { useEffect, useRef, useState } from 'react';
import { Link, useNavigate, useRouter, useRouterState } from '@tanstack/react-router';
import { useQuery, useQueryClient, useSuspenseQuery } from '@tanstack/react-query';
import { AnimatePresence, motion, useReducedMotion } from 'motion/react';
import * as Dialog from '@radix-ui/react-dialog';
import { ArrowLeft, ArrowRight, Bookmark, Check, ChevronRight, Compass, Eye, Heart, Home, Menu, MessageCircle, Play, Plus, Search, Share2, ShieldCheck, ShoppingBag, SlidersHorizontal, Store, User, X } from 'lucide-react';
import type { User as AuthUser } from '@supabase/supabase-js';
import { Button } from '@/components/ui/button';
import { marketSearch, paths, postsQuery, type Mode } from '@/lib/market';
import { dollars, luxuryCategories, luxuryPosts, watchImages, type LuxuryPost } from '@/lib/luxury-market';
import { useMarketPreview } from './market-preview';
import { AuthDialog, UploadForm } from './marketplace';
import { supabase } from '@/integrations/supabase/client';
import { RoleSwitcher, AccountView } from './role-views';
import { ProductComments } from './product-comments';
import { ShortsPlayer } from './shorts-player';
import { BuyerBadge, SellerBadge, SellerRatings } from './reputation';
import { SpecsTable } from './specs-table';
import { type BuyerTier } from '@/lib/reputation';
import { FeedCategoryPicker } from './feed-category-picker';
import { matchesFeedCategory } from '@/lib/feed-categories';
import { SellerDirectory } from './seller-directory';
import { CurrencySelect } from './currency';
import { t } from '@/lib/i18n';
import { InsuranceBanner, InsuranceBreakdown, InsuranceTeaser } from './insurance';
import { ShoppingCollection } from './shopping-collection';
import { sellerIdentity } from '@/lib/seller-directory';
import { ReviewComposer, ReviewList } from './customer-reviews';
import { seedPosts } from '@/lib/seed-sellers';
import { rankRecommended } from '@/lib/feed-ranking';
import { CryptoDepositDialog, CryptoNetworkPicker, type CryptoNetwork } from './crypto-payment';

type View=Mode|'store'|'seller'|'admin';
export function LuxuryMarketplace({mode='home',children,shortsId}:{mode?:View;children?:React.ReactNode;shortsId?:string}) {
 const {data}=useSuspenseQuery(postsQuery); const all=[...luxuryPosts(data),...seedPosts]; const preview=useMarketPreview();
 const location=useRouterState({select:s=>s.location}); const search=marketSearch.parse(location.search);
 const navigate=useNavigate(),router=useRouter(); const base=mode==='store'?'/store':mode==='seller'?'/seller':mode==='admin'?'/admin':paths[mode];
  const sheetPushed=useRef(false),searchPushed=useRef(false),categoriesPushed=useRef(false);
 const [query,setQuery]=useState(search.q || ''),[toast,setToast]=useState(''),[user,setUser]=useState<AuthUser|null>(null),[newest,setNewest]=useState(false);
 useEffect(()=>{const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>setUser(session?.user || null));return ()=>subscription.unsubscribe();},[]);
 const queryClient=useQueryClient();
 useEffect(()=>{const channel=supabase.channel('posts-live').on('postgres_changes',{event:'*',schema:'public',table:'posts'},()=>{void queryClient.invalidateQueries({queryKey:['posts']});}).subscribe();return()=>{void supabase.removeChannel(channel);};},[queryClient]);
 useEffect(()=>{if(!search.shortSheet)sheetPushed.current=false;},[search.shortSheet]);
  useEffect(()=>{if(!search.searchOpen)searchPushed.current=false;},[search.searchOpen]);
 useEffect(()=>setQuery(search.q || ''),[search.q]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(timer);},[toast]);
 const update=(values:Partial<typeof search>)=>{if(shortsId)void navigate({to:'/shorts/$id',params:{id:shortsId},search:prev=>({...prev,...values}),resetScroll:false});else void navigate({to:base,search:prev=>({...prev,...values}),resetScroll:false});};
  const closeCategories=()=>{if(categoriesPushed.current){categoriesPushed.current=false;router.history.back();}else void navigate({to:'/',search:prev=>({...prev,categoriesOpen:undefined}),replace:true,resetScroll:false});};
  const selectCategory=(id:string)=>{categoriesPushed.current=false;void navigate({to:'/',search:prev=>({...prev,feedCategory:id==='recommend'?undefined:id,categoriesOpen:undefined,category:undefined,feedTopic:undefined}),replace:Boolean(search.categoriesOpen),resetScroll:false});};
  const closeSearch=()=>{if(searchPushed.current){searchPushed.current=false;router.history.back();}else if(shortsId)void navigate({to:'/shorts/$id',params:{id:shortsId},search:prev=>({...prev,searchOpen:undefined}),replace:true,resetScroll:false});else void navigate({to:base,search:prev=>({...prev,searchOpen:undefined}),replace:true,resetScroll:false});};
 const close=()=>{if(shortsId)void navigate({to:'/shorts/$id',params:{id:shortsId},search:prev=>({...prev,auth:undefined,panel:undefined}),replace:true,resetScroll:false});else void navigate({to:base,search:prev=>({...prev,...(search.auth?{auth:undefined}:search.menu?{menu:undefined}:search.panel?{panel:undefined}:{post:undefined})}),replace:true,resetScroll:false});};
 let posts=all.filter(p=>!preview.hidden.includes(p.id)&&(!search.q||`${p.title} ${p.creator} ${p.factory} ${p.category}`.toLowerCase().includes(search.q.toLowerCase()))&&(!search.category||search.category==='All'||p.category===search.category||p.factory===search.category));
 if(search.tab==='following') posts=preview.following?posts.filter(p=>p.creator==='VS Watch Studio'):[];
  const storePosts=all.filter(p=>!preview.hidden.includes(p.id)&&(search.seller?(sellerIdentity(p)===search.seller):p.sample));
  if(mode==='store'&&search.seller)posts=posts.filter(p=>storePosts.some(s=>s.id===p.id));
 if(mode==='store'&&search.storeTab==='shorts') posts=posts.filter(p=>p.short);
 if(newest) posts=[...posts].reverse();
 const cleanHome=mode==='home'&&!shortsId;
 if(cleanHome)posts=posts.filter(p=>matchesFeedCategory(p,search.feedCategory));
 const selected=all.find(p=>p.id===(shortsId || search.post));
 const shorts=all.filter(p=>p.short&&!preview.hidden.includes(p.id));
 return <>
 <header className={`lux-header ${cleanHome?'red-home-header':''}`}>
  <div className="lux-header-inner">
  <Button variant="ghost" size="icon" aria-label="Open menu" onClick={()=>update({menu:true})}><Menu/></Button>
    <Link to="/" search={{role:search.role}} className="lux-brand" aria-label="VELA home">VELA</Link>
    <nav className="lux-header-tabs" aria-label="Feed tabs">{[['following','팔로잉'],['discover','추천'],['reviews','리뷰']].map(([tab,label])=><Button asChild variant="ghost" key={tab} className={`lux-tab ${(search.tab || 'discover')===tab?'active':''}`}><Link to="/" search={{role:search.role,feedCategory:search.feedCategory,tab:tab as 'following'|'discover'|'reviews'}} aria-current={(search.tab || 'discover')===tab?'page':undefined} resetScroll={false}>{label}</Link></Button>)}</nav>
   <CurrencySelect/><Button variant="ghost" size="icon" aria-label="Open search" onClick={()=>{searchPushed.current=true;update({searchOpen:true});}}><Search/></Button>
  </div>
   {cleanHome&&<FeedCategoryPicker selected={search.feedCategory} open={Boolean(search.categoriesOpen)} onOpen={()=>{categoriesPushed.current=true;update({categoriesOpen:true});}} onClose={closeCategories} onSelect={selectCategory}/>}
 </header>
  <main className={`lux-shell ${cleanHome?'red-home-shell':''} ${mode==='admin'?'backoffice-shell':''}`}>
 {(mode==='explore'||mode==='market')&&<>
 {mode==='explore'&&<form className="lux-search" onSubmit={e=>{e.preventDefault();update({q:query || undefined});}}><Search size={18}/><input autoFocus aria-label="Search watches" placeholder="Search watches, factories, studios…" value={query} onChange={e=>setQuery(e.target.value)}/><Button variant="ghost" size="icon" type="submit" aria-label="Search"><ArrowRight/></Button></form>}
 <nav className="lux-categories" aria-label="Categories">{luxuryCategories.map(category=><Button asChild key={category} variant="ghost" className={`lux-chip ${(search.category || 'All')===category?'active':''}`}><Link to={base} search={prev=>({...prev,category:category==='All'?undefined:category})} resetScroll={false}>{category}</Link></Button>)}<Button variant="ghost" size="icon" className="shrink-0" aria-label="Toggle newest first" aria-pressed={newest} onClick={()=>setNewest(p=>!p)}><SlidersHorizontal/></Button></nav>
 <div className="lux-feed-heading"><div><span className="lux-eyebrow">THE EDIT · OCTOBER 2026</span><h1>{search.q?`Results for “${search.q}”`:search.tab==='following'?'From your studios':mode==='market'?'The watch collection':'Exceptional finds.'}</h1></div><span className="curated-label"><span className="status-dot"/>Curated daily</span></div>
 </>}
 {cleanHome&&search.tab==='reviews'?<section className="mt-4 grid gap-4"><ReviewComposer requestAuth={()=>update({auth:true})}/><ReviewList role={search.role}/></section>:
 mode==='me'?<AccountView posts={all} user={user} onPanel={panel=>update({panel})} requestAuth={()=>update({auth:true})}/>:
 mode==='upload'?<><div className="sample-notice">Product publishing · Account sign-in required</div><UploadForm user={user} requestAuth={()=>update({auth:true})} onPosted={()=>{void router.invalidate();void navigate({to:'/me',search:{role:search.role}});}}/></>:
  mode==='store'?search.seller?<><SellerStoreHeader post={storePosts[0]} count={storePosts.length} search={search}/>{search.storeTab==='reviews'?<><h2 className="mt-6 text-base font-semibold">고객 리뷰</h2><ReviewList sellerId={search.seller} role={search.role}/></>:<Feed posts={posts} base={base} search={search}/>}</>:<><InsuranceBanner role={search.role}/><SellerDirectory posts={all.filter(p=>!preview.hidden.includes(p.id))} category={search.storeCategory} role={search.role}/></>:
  mode==='admin'||mode==='seller'?children:<div className="lux-feed-transition" key={search.tab || 'discover'}><Feed posts={posts} base={base} search={search}/></div>}
 </main>
 <nav className="lux-bottom-nav" aria-label="Main navigation"><div>
  <Button asChild variant="ghost" className={`lux-nav-item ${mode==='home'&&!search.panel?'active':''}`}><Link to="/" search={{role:search.role}}><Home/><span>메인 페이지</span></Link></Button>
  <Button asChild variant="ghost" className={`lux-nav-item ${mode==='store'?'active':''}`}><Link to="/store" search={{role:search.role}}><Store/><span>스토어</span></Link></Button>
  {search.role==='seller'||search.role==='admin'?<Button asChild variant="gold" className="lux-upload" aria-label="Add product or short"><Link to="/upload" search={{role:search.role}}><Plus/></Link></Button>:<Button asChild variant="gold" className="lux-upload lux-buyer-bag" aria-label="Shopping bag and saved items"><Link to="/me" search={{role:search.role,panel:'cart'}}><ShoppingBag/>{preview.cart.length>0&&<span className="bag-count">{preview.cart.length}</span>}</Link></Button>}
  <Button asChild variant="ghost" className={`lux-nav-item ${search.panel==='chat'?'active':''}`}><Link to={base} search={prev=>({...prev,panel:'chat'})} resetScroll={false}><MessageCircle/><span>메시지</span></Link></Button>
  <Button asChild variant="ghost" className={`lux-nav-item ${mode==='me'?'active':''}`}><Link to="/me" search={{role:search.role}}><User/><span>나</span></Link></Button>
</div></nav>

 <AnimatePresence>{selected&&!shortsId&&<ProductDetail key={selected.id} post={selected} user={user} requestAuth={()=>update({auth:true})} close={close} onPanel={panel=>update({panel})} notify={setToast}/>}</AnimatePresence>
  {shortsId&&(shorts.some(p=>p.id===shortsId)?<ShortsPlayer posts={shorts} selectedId={shortsId} sheet={search.shortSheet} shortTab={search.shortTab || 'recommend'} onTab={shortTab=>update({shortTab})} onSearch={()=>{searchPushed.current=true;update({searchOpen:true});}} user={user} close={()=>void navigate({to:'/',search:{role:search.role},replace:true})} closeSheet={()=>{if(sheetPushed.current){sheetPushed.current=false;router.history.back();}else void navigate({to:'/shorts/$id',params:{id:shortsId},search:prev=>({...prev,shortSheet:undefined,shortPhoto:undefined}),replace:true,resetScroll:false});}} change={id=>void navigate({to:'/shorts/$id',params:{id},search:prev=>({...prev,shorts:undefined}),replace:true,resetScroll:false})} openSheet={shortSheet=>{sheetPushed.current=true;update({shortSheet});}} requestAuth={()=>update({auth:true})} buy={box=>update({panel:'checkout',checkoutBox:Boolean(box)})} notify={setToast}/>:<Overlay title="Short unavailable" close={()=>void navigate({to:'/',search:{role:search.role},replace:true})}><Button asChild variant="goldOutline"><Link to="/" search={{role:search.role}}>Return Home</Link></Button></Overlay>)}
  {search.searchOpen&&<Dialog.Root open onOpenChange={open=>{if(!open)closeSearch();}}><Dialog.Portal><Dialog.Overlay className="lux-backdrop overlay-front"/><Dialog.Content className="lux-search-overlay" aria-describedby={undefined}><div className="lux-search-overlay-inner"><div className="lux-search-top"><Dialog.Title className="text-lg font-semibold">Search</Dialog.Title><Button variant="ghost" size="icon" aria-label="Close search" onClick={closeSearch}><X/></Button></div><form className="lux-search" onSubmit={e=>{e.preventDefault();void navigate({to:'/explore',search:{role:search.role,q:query.trim() || undefined},replace:true});}}><Search size={18}/><input autoFocus aria-label="Search watches" placeholder="Search watches, factories, studios…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<Button variant="ghost" size="icon" type="button" aria-label="Clear search" onClick={()=>setQuery('')}><X/></Button>}<Button variant="ghost" size="icon" type="submit" aria-label="Search"><ArrowRight/></Button></form><div className="lux-search-results"><Feed posts={all.filter(p=>!preview.hidden.includes(p.id)&&`${p.title} ${p.creator} ${p.factory} ${p.category}`.toLowerCase().includes(query.trim().toLowerCase()))} base={base} search={{role:search.role}}/></div></div></Dialog.Content></Dialog.Portal></Dialog.Root>}
 {search.menu&&<Overlay title="velamarket" close={close} side><div className="menu-links">{[['/','Discover'],['/market','Watch collection'],['/store','VS Watch Studio'],['/me','My Vela']].map(([to,label])=><Button asChild variant="ghost" key={to}><Link to={to as '/'} search={{role:search.role}}>{label}<ChevronRight/></Link></Button>)}</div><div className="mt-8 border-t border-border pt-6"><span className="lux-eyebrow">VIEW AS · SAMPLE ACCOUNTS</span><RoleSwitcher/></div><p className="mt-8 text-xs leading-6 text-muted-foreground">벨라마켓 · A considered collection.</p></Overlay>}
 {search.post&&!selected&&<Overlay title="Product unavailable" close={close}><p className="py-6 text-sm text-muted-foreground">This listing is no longer available.</p></Overlay>}
 {search.auth&&<AuthDialog onClose={close} onSignedIn={close}/>}
 {search.panel&&<CommercePanel posts={all} onBuy={post=>update({checkoutItem:post.id,panel:'checkout'})} panel={search.panel} selected={search.panel==='checkout'&&search.checkoutItem?all.find(post=>post.id===search.checkoutItem):selected} close={close} onPanel={panel=>update({panel})} notify={setToast}/>}
 {toast&&<div className="lux-toast" role="status"><Check size={16}/>{toast}</div>}
 </>;
}
function Feed({posts,base,search}:{posts:LuxuryPost[];base:'/'|'/explore'|'/market'|'/me'|'/upload'|'/store'|'/seller'|'/admin';search:ReturnType<typeof marketSearch.parse>}) {
 const preview=useMarketPreview();const compact=base==='/';const columns=compact?2:3;
 return posts.length?<div className={`lux-waterfall ${compact?'red-home-waterfall':''}`}>{Array.from({length:columns},(_,i)=>i).map(column=><div className="lux-column" key={column}>{posts.filter((_,i)=>i%columns===column).map((post,i)=><article className="lux-post" key={post.id}>
  <Link to={post.short?'/shorts/$id':base} params={post.short?{id:post.id}:{}} search={post.short?{role:search.role}:{...search,post:post.id,shorts:undefined}} resetScroll={false} className={`lux-post-media shape-${(column+i)%3}`} aria-label={post.title}>{post.video?<video src={post.video} autoPlay muted loop playsInline preload={i===0?'auto':'metadata'} aria-label={`${post.title} 영상`}/>:<img src={post.images[0]} alt={post.title} width={512} height={512} loading={i===0?'eager':'lazy'} onError={e=>{e.currentTarget.onerror=null;e.currentTarget.src=watchImages[0] ?? '';}}/>}{!compact&&<><span className="lux-views"><Eye size={12}/>{post.views}<span className="views-word"> views</span></span><span className="lux-bag"><ShoppingBag size={15}/></span></>}</Link>
 <div className="lux-post-copy">{!compact&&<div className="lux-post-tags"><span>{post.factory}</span>{(preview.audits[post.id]?preview.audits[post.id]==='Approved':post.verified)&&<ShieldCheck size={12}/>}</div>}<Link to={post.short?'/shorts/$id':base} params={post.short?{id:post.id}:{}} search={post.short?{role:search.role}:{...search,post:post.id,shorts:undefined}} resetScroll={false}><h2>{post.title}</h2></Link>{!compact&&post.price!==null&&<p className="lux-card-price">{dollars(post.price)}</p>}<div className="lux-post-creator" data-no-translate><Link to="/store" search={{role:search.role,seller:sellerIdentity(post)}}><img src={post.images[0]} width={20} height={20} alt=""/><span>{post.creator}</span><SellerBadge reputation={post.reputation} compact/></Link><Button variant="ghost" className={`lux-heart ${preview.saved.includes(post.id)?'active':''}`} aria-label={`Save ${post.title}`} aria-pressed={preview.saved.includes(post.id)} onClick={()=>preview.toggleSaved(post.id)}><Heart/>{compact?new Intl.NumberFormat('ko-KR',{notation:'compact',maximumFractionDigits:1}).format(post.likes+(preview.saved.includes(post.id)?1:0)):post.likes+(preview.saved.includes(post.id)?1:0)}</Button></div></div>
 </article>)}</div>)}</div>:<div className="lux-empty"><Compass/><h2>No finds here yet.</h2><p>Follow a studio or choose another category.</p><Button asChild variant="goldOutline"><Link to="/store">Explore VS Watch Studio<ArrowRight/></Link></Button></div>;
}
function ProductDetail({post,user,requestAuth,close,onPanel,notify}:{post:LuxuryPost;user:AuthUser|null;requestAuth:()=>void;close:()=>void;onPanel:(panel:'chat'|'cart'|'checkout')=>void;notify:(s:string)=>void}) {
 const preview=useMarketPreview(),reduced=useReducedMotion();const carousel=useRef<HTMLDivElement>(null);const [slide,setSlide]=useState(0);
 const verified=preview.audits[post.id]?preview.audits[post.id]==='Approved':post.verified;
 return <Dialog.Root open onOpenChange={open=>{if(!open)close();}}><Dialog.Portal><Dialog.Overlay asChild><motion.div className="lux-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/></Dialog.Overlay><Dialog.Content asChild aria-describedby={undefined}><motion.div className="lux-detail" initial={{y:reduced?0:'100%'}} animate={{y:0}} exit={{y:reduced?0:'100%'}} transition={{type:'spring',damping:32,stiffness:300}}>
 <div className="lux-detail-top"><Button variant="ghost" size="icon" aria-label="Close product" onClick={close}><ArrowLeft/></Button><Link to="/store" search={{seller:sellerIdentity(post)}} className="detail-seller" data-no-translate><img src={post.images[0]} width={32} height={32} alt=""/><span><span className="seller-name-line">{post.creator}<SellerBadge reputation={post.reputation} compact/></span><small>Watchmaker & curator</small></span></Link><Button variant="goldOutline" size="sm" onClick={preview.follow}>{preview.following?<Check size={12}/>:<Plus size={12}/>}<span>{preview.following?'Following':'Follow'}</span></Button><Button variant="ghost" size="icon" aria-label="Share product" onClick={async()=>{try{if(navigator.share)await navigator.share({title:post.title,url:window.location.href});else{await navigator.clipboard.writeText(window.location.href);notify('Product link copied');}}catch{/* cancelled */}}}><Share2/></Button></div>
 <div className="lux-detail-scroll"><div className="lux-carousel-wrap"><div className="lux-carousel" ref={carousel} onScroll={e=>setSlide(Math.round(e.currentTarget.scrollLeft/e.currentTarget.clientWidth))}>{post.video&&<video src={post.video} poster={post.images[0]} controls playsInline preload="metadata"/>}{post.images.map((src,i)=><img key={i} src={src} width={512} height={512} alt={`${post.title} · 상세 사진 ${i+1}`}/>)}</div><span className="lux-counter">{slide+1}/{post.images.length+(post.video?1:0)}</span>{verified&&<span className="lux-verified"><ShieldCheck size={14}/> VELA VERIFIED</span>}{post.short&&!post.video&&<span className="sample-media-label">Shorts · Still preview</span>}</div>
  {post.images.length+(post.video?1:0)>1&&<div className="carousel-controls"><Button size="icon" variant="ghost" aria-label="Previous media" disabled={slide===0} onClick={()=>carousel.current?.scrollBy({left:-(carousel.current.clientWidth),behavior:reduced?'auto':'smooth'})}><ArrowLeft/></Button>{Array.from({length:post.images.length+(post.video?1:0)},(_,i)=><span key={i} className={`carousel-dot ${slide===i?'active':''}`}/>)}<Button size="icon" variant="ghost" aria-label="Next media" disabled={slide===post.images.length+(post.video?1:0)-1} onClick={()=>carousel.current?.scrollBy({left:carousel.current.clientWidth,behavior:reduced?'auto':'smooth'})}><ArrowRight/></Button></div>}
 <div className="lux-detail-copy"><div className="flex flex-wrap items-center justify-between gap-3">{post.price!==null&&<p className="lux-price">{dollars(post.price)}</p>}<span className="text-xs text-muted-foreground"><Eye size={13} className="mr-1 inline"/>{post.views} views</span></div><Dialog.Title className="mt-4 text-xl font-semibold leading-relaxed">{post.title}</Dialog.Title><div className="detail-tags"><span>{post.factory}</span><span>{post.category}</span>{post.sample&&<span>Studio sample</span>}</div><p className="mt-5 text-sm leading-7 text-muted-foreground">{post.description}</p><SpecsTable specs={post.source.specs} fallback={<dl className="lux-specs"><div><dt>Specification</dt><dd>1:1 studio specification</dd></div><div><dt>Case & bracelet</dt><dd>Stainless steel</dd></div><div><dt>Crystal</dt><dd>Sapphire</dd></div><div><dt>Movement</dt><dd>Automatic mechanical</dd></div></dl>}/><p className="mt-5 text-xs leading-6 text-primary">#WatchCommunity #Automatic #{post.factory.replaceAll(' ','')} #VelaFinds</p><div className="mt-7 border-t border-border pt-5"><h3 className="text-sm font-medium">Studio notes</h3><p className="mt-2 text-xs leading-6 text-muted-foreground">{post.sample?'Sample product, pricing and verification. No brand affiliation or real inspection claim.':'Contact the studio to confirm specifications and availability.'}</p></div><EscrowGuarantee/>{post.price!==null&&<InsuranceTeaser price={post.price} format={dollars}/>}<SellerRatings reputation={post.reputation}/><ProductComments postId={post.id} user={user} requestAuth={requestAuth}/></div></div>
 <div className="lux-detail-actions"><Button variant="ghost" size="icon" aria-label="Chat with seller" onClick={()=>onPanel('chat')}><MessageCircle/></Button><Button variant="ghost" size="icon" aria-label="Save product" aria-pressed={preview.saved.includes(post.id)} className={preview.saved.includes(post.id)?'text-primary':''} onClick={()=>preview.toggleSaved(post.id)}><Bookmark fill={preview.saved.includes(post.id)?'currentColor':'none'}/></Button><Button variant="goldOutline" onClick={()=>{preview.addCart(post);notify('Added to your sample shopping bag');}}>{t('addCart')}</Button><Button variant="gold" onClick={()=>onPanel('checkout')}>{t('buyNow')}<ArrowRight size={14}/></Button></div>
 </motion.div></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
export function Overlay({title,close,children,side=false}:{title:string;close:()=>void;children:React.ReactNode;side?:boolean}) {
 return <Dialog.Root open onOpenChange={open=>{if(!open)close();}}><Dialog.Portal><Dialog.Overlay className="lux-backdrop overlay-front"/><Dialog.Content className={side?'lux-menu':'lux-dialog'} aria-describedby={undefined}><div className="flex items-center justify-between gap-3"><Dialog.Title className="text-xl font-semibold">{title}</Dialog.Title><Button variant="ghost" size="icon" aria-label="Close dialog" onClick={close}><X/></Button></div>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>;
}
function CommercePanel({posts,onBuy,panel,selected,close,onPanel,notify}:{posts:LuxuryPost[];onBuy:(post:LuxuryPost)=>void;panel:string;selected:LuxuryPost|undefined;close:()=>void;onPanel:(panel:'checkout')=>void;notify:(s:string)=>void}) {
 const preview=useMarketPreview();const [sent,setSent]=useState(false),[message,setMessage]=useState(''),[messages,setMessages]=useState<string[]>([]);
 const item=selected || preview.cart[0];
 return <Overlay title={({chat:'Chat with studio',cart:'Your shopping bag',checkout:'Order preview',settings:'Profile settings',apply:'Become a Vela seller',orders:'Escrow order board'} as Record<string,string>)[panel] || 'My Vela'} close={close}>
 {panel==='chat'?<><p className="sample-notice">Sample conversation · Messages are not delivered</p><div className="chat-bubble">VS Watch Studio: Hello. Which details would you like to see?</div>{messages.map((m,i)=><div className="chat-bubble outgoing" key={i}>{m}</div>)}<form className="mt-6 flex gap-2" onSubmit={e=>{e.preventDefault();if(message.trim()){setMessages(p=>[...p,message.trim()]);setMessage('');}}}><input className="form-input" aria-label="Message to seller" value={message} onChange={e=>setMessage(e.target.value)} placeholder="Ask about the watch…"/><Button type="submit" variant="gold" size="icon" aria-label="Send sample message"><ArrowRight/></Button></form></>:
 panel==='cart'?<ShoppingCollection posts={posts} onBuy={onBuy}/>: panel==='checkout'?sent?<div className="py-8 text-center"><Check className="mx-auto mb-4 text-primary" size={36}/><h2 className="text-lg font-semibold">Sample order created</h2><p className="mt-3 text-sm text-muted-foreground">Awaiting payment. No charge has been made.</p><Button asChild variant="goldOutline" className="mt-6"><Link to="/me" search={{panel:'orders'}}>View orders</Link></Button></div>:<><p className="sample-notice">Preview checkout · Payment is not connected</p>{item?<CheckoutForm item={item} onDone={()=>setSent(true)}/>:<p className="py-8 text-muted-foreground">Add a product to your bag first.</p>}</>:
 panel==='apply'?<SellerOnboarding/>:
 panel==='orders'?<BuyerOrderBoard/>:
 <form className="mt-5" onSubmit={e=>{e.preventDefault();const fields=new FormData(e.currentTarget);const t=(k:string,n=200)=>String(fields.get(k) ?? '').trim().slice(0,n);preview.saveProfile({name:t('displayName',60) || 'Vela Member',region:t('region') || 'Global',recipient:t('recipient',60),phone:t('phone',30),address:t('address',300),postal:t('postal',12)});notify('Sample profile updated for this preview');close();}}><p className="sample-notice">Sample profile settings</p><label className="form-label" htmlFor="profile-name">Display name</label><input id="profile-name" name="displayName" className="form-input" defaultValue={preview.profile.name} required/><label className="form-label" htmlFor="profile-region">Region</label><select id="profile-region" name="region" className="form-input" defaultValue={preview.profile.region}><option>Global</option><option>Mainland China</option><option>South Korea</option></select><h3 className="mt-6 text-sm font-semibold">배송 정보</h3><label className="form-label" htmlFor="profile-recipient">수령인</label><input id="profile-recipient" name="recipient" className="form-input" maxLength={60} autoComplete="name" defaultValue={preview.profile.recipient}/><label className="form-label" htmlFor="profile-phone">연락처</label><input id="profile-phone" name="phone" type="tel" className="form-input" maxLength={30} autoComplete="tel" defaultValue={preview.profile.phone}/><label className="form-label" htmlFor="profile-address">배송 주소</label><textarea id="profile-address" name="address" className="form-input" maxLength={300} autoComplete="street-address" defaultValue={preview.profile.address}/><label className="form-label" htmlFor="profile-postal">우편번호</label><input id="profile-postal" name="postal" className="form-input" maxLength={12} autoComplete="postal-code" defaultValue={preview.profile.postal}/><Button variant="gold" className="mt-6 w-full" type="submit">Save profile</Button></form>}
 </Overlay>;
}
function SellerStoreHeader({post,count,search}:{post:LuxuryPost|undefined;count:number;search:ReturnType<typeof marketSearch.parse>}) {
 const preview=useMarketPreview(),following=post?.sample?preview.following:preview.followedSellers.includes(search.seller ?? '');
 return <><div className="store-profile mt-8">{post&&<img src={post.images[0]} className="store-avatar" alt={post.creator}/>}<div className="store-title" data-no-translate><h1>{post?.creator || 'Seller unavailable'}{post&&<SellerBadge reputation={post.reputation}/>}</h1>{post&&<Button variant="goldOutline" aria-pressed={following} onClick={()=>preview.toggleSeller(sellerIdentity(post))}>{following?<Check/>:<Plus/>}{following?'Following':'Follow'}</Button>}</div>{post&&<p className="store-bio">{post.sample?'Independent watch curation. Thoughtful details, precise movements.':post.description}</p>}<div className="store-stats"><span><strong>{count}</strong> Products</span></div>{post&&<SellerRatings reputation={post.reputation}/>}</div><nav className="lux-tabs store-tabs">{(['products','shorts','reviews'] as const).map(tab=><Button key={tab} asChild variant="ghost" className={`lux-tab ${(search.storeTab || 'products')===tab?'active':''}`}><Link to="/store" search={{role:search.role,seller:search.seller,storeTab:tab}}>{tab==='reviews'?'Customer Reviews':`${tab[0]?.toUpperCase()}${tab.slice(1)}`}</Link></Button>)}</nav></>;
}
function Reviews(){const memberships:BuyerTier[]=['black','gold','silver'];return <div className="review-list">{[['A. Chen','Beautiful finishing. The studio shared detailed photos before shipping.'],['J. Park','Quick communication and a carefully packed watch.'],['M. Lee','The dial looks even better in person.']].map(([name,text],index)=><article key={name}><div className="flex justify-between"><div className="review-author"><strong>{name}</strong><BuyerBadge tier={memberships[index] ?? 'member'}/></div><span className="text-primary">★★★★★</span></div><p className="mt-3 text-sm leading-7 text-muted-foreground">{text}</p><span className="mt-3 block text-xs text-muted-foreground">Sample review · Verified purchase preview</span></article>)}</div>;}

function CheckoutForm({item,onDone}:{item:LuxuryPost;onDone:()=>void}){
 const preview=useMarketPreview(),p=preview.profile;
 const checkoutSearch=useRouterState({select:s=>marketSearch.parse(s.location.search)});
 const [box,setBox]=useState(Boolean(checkoutSearch.checkoutBox));
 const [f,setF]=useState({recipient:p.recipient||'',phone:p.phone,address:p.address,postal:p.postal,region:['Mainland China','South Korea','Global'].includes(p.region)?p.region:'Global'});
 const filled=Boolean(p.recipient&&p.phone&&p.address);
 const set=(k:keyof typeof f)=>(e:{target:{value:string}})=>setF(prev=>({...prev,[k]:e.target.value}));
 const price=item.price ?? 0, boxPrice=item.boxPrice ?? 0;
 const [network,setNetwork]=useState<CryptoNetwork>('USDT-TRC20'); const [deposit,setDeposit]=useState(false);
 return <form onSubmit={e=>{e.preventDefault();setDeposit(true);}}>
  <div className="cart-line"><img src={item.images[0]} width={64} height={64} alt=""/><div><p>{item.title}</p><p className="mt-2 text-primary">{dollars(price)}</p></div></div>
  {boxPrice>0&&<label className="box-option"><input type="checkbox" checked={box} onChange={e=>setBox(e.target.checked)} className="size-4 accent-primary"/><span>{t('addBox')}</span><strong>+{dollars(boxPrice)}</strong></label>}
  <InsuranceBreakdown price={price} box={box?boxPrice:0} format={dollars}/>
  <h3 className="mt-6 text-sm font-semibold">{t('shippingInfo')}</h3>
  <p className="mt-1 text-xs text-muted-foreground">{filled?t('autofilled'):t('manualEntry')}</p>
  <label className="form-label" htmlFor="checkout-name">{t('recipient')}</label><input id="checkout-name" className="form-input" required maxLength={60} autoComplete="name" value={f.recipient} onChange={set('recipient')}/>
  <label className="form-label" htmlFor="checkout-phone">{t('phone')}</label><input id="checkout-phone" type="tel" className="form-input" required maxLength={30} autoComplete="tel" value={f.phone} onChange={set('phone')}/>
  <label className="form-label" htmlFor="checkout-address">{t('address')}</label><textarea id="checkout-address" className="form-input" required maxLength={300} autoComplete="street-address" value={f.address} onChange={set('address')}/>
  <label className="form-label" htmlFor="checkout-postal">{t('postal')}</label><input id="checkout-postal" className="form-input" required maxLength={12} autoComplete="postal-code" value={f.postal} onChange={set('postal')}/>
  <label className="form-label" htmlFor="checkout-region">{t('destination')}</label><select id="checkout-region" className="form-input" value={f.region} onChange={set('region')}><option>Mainland China</option><option>South Korea</option><option>Global</option></select>
  <CryptoNetworkPicker value={network} onChange={setNetwork}/>
  <p className="my-5 text-xs leading-6 text-muted-foreground">{t('shippingNote')}</p>
  <Button variant="gold" className="w-full" type="submit">암호화폐로 결제하기<ArrowRight/></Button>
  {deposit&&<CryptoDepositDialog network={network} usd={price+(box?boxPrice:0)} onClose={()=>setDeposit(false)} onSubmit={()=>{setDeposit(false);preview.order(item);onDone();}}/>}
 </form>;
}
