import { useEffect, useRef, useState } from 'react';
import { Link, useNavigate, useRouter, useRouterState } from '@tanstack/react-router';
import { useSuspenseQuery } from '@tanstack/react-query';
import { AnimatePresence, motion, useReducedMotion } from 'motion/react';
import * as Dialog from '@radix-ui/react-dialog';
import { ArrowLeft, ArrowRight, Bookmark, Check, ChevronRight, Compass, Eye, Heart, Home, Menu, MessageCircle, Play, Plus, Search, Share2, ShieldCheck, ShoppingBag, SlidersHorizontal, User, X } from 'lucide-react';
import type { User as AuthUser } from '@supabase/supabase-js';
import { Button } from '@/components/ui/button';
import { marketSearch, paths, postsQuery, type Mode } from '@/lib/market';
import { dollars, luxuryCategories, luxuryPosts, watchImages, type LuxuryPost } from '@/lib/luxury-market';
import { useMarketPreview } from './market-preview';
import { AuthDialog, UploadForm } from './marketplace';
import { supabase } from '@/integrations/supabase/client';
import { RoleSwitcher, AccountView } from './role-views';
import { ProductComments } from './product-comments';

type View=Mode|'store'|'seller'|'admin';
export function LuxuryMarketplace({mode='home',children}:{mode?:View;children?:React.ReactNode}) {
 const {data}=useSuspenseQuery(postsQuery); const all=luxuryPosts(data); const preview=useMarketPreview();
 const location=useRouterState({select:s=>s.location}); const search=marketSearch.parse(location.search);
 const navigate=useNavigate(),router=useRouter(); const base=mode==='store'?'/store':mode==='seller'?'/seller':mode==='admin'?'/admin':paths[mode];
 const [query,setQuery]=useState(search.q || ''),[toast,setToast]=useState(''),[user,setUser]=useState<AuthUser|null>(null),[newest,setNewest]=useState(false);
 useEffect(()=>{const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>setUser(session?.user || null));return ()=>subscription.unsubscribe();},[]);
 useEffect(()=>setQuery(search.q || ''),[search.q]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(timer);},[toast]);
 const update=(values:Partial<typeof search>)=>void navigate({to:base,search:prev=>({...prev,...values}),resetScroll:false});
 const close=()=>void navigate({to:base,search:prev=>({...prev,...(search.auth?{auth:undefined}:search.menu?{menu:undefined}:search.panel?{panel:undefined}:{post:undefined})}),replace:true,resetScroll:false});
 let posts=all.filter(p=>!preview.hidden.includes(p.id)&&(!search.q||`${p.title} ${p.creator} ${p.factory} ${p.category}`.toLowerCase().includes(search.q.toLowerCase()))&&(!search.category||search.category==='All'||p.category===search.category||p.factory===search.category));
 if(search.tab==='following') posts=preview.following?posts.filter(p=>p.creator==='VS Watch Studio'):[];
 if(mode==='store'&&search.storeTab==='shorts') posts=posts.filter(p=>p.short);
 if(newest) posts=[...posts].reverse();
 const selected=all.find(p=>p.id===search.post);
 return <>
 <main className={`lux-shell ${mode==='admin'?'backoffice-shell':''}`}>
 <header className="lux-header">
  <Button variant="ghost" size="icon" aria-label="Open menu" onClick={()=>update({menu:true})}><Menu/></Button>
  <Link to="/" search={{role:search.role}} className="lux-brand" aria-label="velamarket home"><span className="brand-symbol">V</span><span>vela<span className="font-normal">market</span><span className="text-primary">.</span></span></Link>
  <div className="flex items-center gap-2"><Button variant="ghost" size="icon" aria-label="Open search" asChild><Link to="/explore" search={{role:search.role}}><Search/></Link></Button><Button variant="ghost" size="icon" className="desktop-only" aria-label="Shopping bag" onClick={()=>update({panel:'cart'})}><ShoppingBag/>{preview.cart.length>0&&<span className="cart-count">{preview.cart.length}</span>}</Button></div>
 </header>
 {(mode==='home'||mode==='explore'||mode==='market')&&<>
 <nav className="lux-tabs" aria-label="Feed tabs">{[['following','Following'],['discover','For You'],['nearby','Explore']].map(([tab,label])=><Button asChild variant="ghost" key={tab} className={`lux-tab ${(search.tab || 'discover')===tab?'active':''}`}><Link to="/" search={{role:search.role,tab:tab as 'following'|'discover'|'nearby'}} resetScroll={false}>{label}</Link></Button>)}</nav>
 {mode==='explore'&&<form className="lux-search" onSubmit={e=>{e.preventDefault();update({q:query || undefined});}}><Search size={18}/><input autoFocus aria-label="Search watches" placeholder="Search watches, factories, studios…" value={query} onChange={e=>setQuery(e.target.value)}/><Button variant="ghost" size="icon" type="submit" aria-label="Search"><ArrowRight/></Button></form>}
 <nav className="lux-categories" aria-label="Categories">{luxuryCategories.map(category=><Button asChild key={category} variant="ghost" className={`lux-chip ${(search.category || 'All')===category?'active':''}`}><Link to={base} search={prev=>({...prev,category:category==='All'?undefined:category})} resetScroll={false}>{category}</Link></Button>)}<Button variant="ghost" size="icon" className="shrink-0" aria-label="Toggle newest first" aria-pressed={newest} onClick={()=>setNewest(p=>!p)}><SlidersHorizontal/></Button></nav>
 <div className="lux-feed-heading"><div><span className="lux-eyebrow">THE EDIT · OCTOBER 2026</span><h1>{search.q?`Results for “${search.q}”`:search.tab==='following'?'From your studios':mode==='market'?'The watch collection':'Exceptional finds.'}</h1></div><span className="curated-label"><span className="status-dot"/>Curated daily</span></div>
 </>}
 {mode==='me'?<AccountView posts={all} user={user} onPanel={panel=>update({panel})} requestAuth={()=>update({auth:true})}/>:
 mode==='upload'?<><div className="sample-notice">Product publishing · Account sign-in required</div><UploadForm user={user} requestAuth={()=>update({auth:true})} onPosted={()=>{void router.invalidate();void navigate({to:'/me',search:{role:search.role}});}}/></>:
 mode==='store'?<><StoreHeader tab={search.storeTab || 'products'} role={search.role}/>{search.storeTab==='reviews'?<Reviews/>:<Feed posts={posts} base={base} search={search}/>}</>:
 mode==='admin'||mode==='seller'?children:<Feed posts={posts} base={base} search={search}/>}
 </main>
 <nav className="lux-bottom-nav" aria-label="Main navigation"><div>
 {[['/','home',Home,'Home'],['/explore','explore',Compass,'Explore']].map(([to,m,Icon,label])=>{const I=Icon as typeof Home;return <Link key={String(to)} to={to as '/'} search={{role:search.role}} className={`lux-nav-item ${mode===m?'active':''}`}><I/><span>{String(label)}</span></Link>;})}
 <Button asChild variant="gold" className="lux-upload" aria-label="Add product or short"><Link to="/upload" search={{role:search.role}}><Plus/></Link></Button>
 <Link to="/market" search={{role:search.role}} className={`lux-nav-item ${mode==='market'?'active':''}`}><ShoppingBag/><span>Market</span></Link>
 <Link to="/me" search={{role:search.role}} className={`lux-nav-item ${mode==='me'?'active':''}`}><User/><span>My Vela</span></Link>
 </div></nav>
 <AnimatePresence>{selected&&<ProductDetail key={selected.id} post={selected} user={user} requestAuth={()=>update({auth:true})} close={close} onPanel={panel=>update({panel})} notify={setToast}/>}</AnimatePresence>
 {search.menu&&<Overlay title="velamarket" close={close} side><div className="menu-links">{[['/','Discover'],['/market','Watch collection'],['/store','VS Watch Studio'],['/me','My Vela']].map(([to,label])=><Button asChild variant="ghost" key={to}><Link to={to as '/'} search={{role:search.role}}>{label}<ChevronRight/></Link></Button>)}</div><div className="mt-8 border-t border-border pt-6"><span className="lux-eyebrow">VIEW AS · SAMPLE ACCOUNTS</span><RoleSwitcher/></div><p className="mt-8 text-xs leading-6 text-muted-foreground">벨라마켓 · A considered collection.</p></Overlay>}
 {search.post&&!selected&&<Overlay title="Product unavailable" close={close}><p className="py-6 text-sm text-muted-foreground">This listing is no longer available.</p></Overlay>}
 {search.auth&&<AuthDialog onClose={close} onSignedIn={close}/>}
 {search.panel&&<CommercePanel panel={search.panel} selected={selected} close={close} onPanel={panel=>update({panel})} notify={setToast}/>}
 {toast&&<div className="lux-toast" role="status"><Check size={16}/>{toast}</div>}
 </>;
}
function Feed({posts,base,search}:{posts:LuxuryPost[];base:'/'|'/explore'|'/market'|'/me'|'/upload'|'/store'|'/seller'|'/admin';search:ReturnType<typeof marketSearch.parse>}) {
 const preview=useMarketPreview();
 return posts.length?<div className="lux-waterfall">{[0,1,2].map(column=><div className="lux-column" key={column}>{posts.filter((_,i)=>i%3===column).map((post,i)=><article className="lux-post" key={post.id}>
 <Link to={base} search={{...search,post:post.id}} resetScroll={false} className={`lux-post-media shape-${(column+i)%3}`} aria-label={post.title}><img src={post.images[0]} alt={post.title} width={512} height={512} loading={i===0?'eager':'lazy'} onError={e=>{e.currentTarget.onerror=null;e.currentTarget.src=watchImages[0] ?? '';}}/>{post.short&&<span className="lux-play"><Play size={13} fill="currentColor"/></span>}<span className="lux-views"><Eye size={12}/>{post.views}<span className="views-word"> views</span></span><span className="lux-bag"><ShoppingBag size={15}/></span></Link>
 <div className="lux-post-copy"><div className="lux-post-tags"><span>{post.factory}</span>{(preview.audits[post.id]?preview.audits[post.id]==='Approved':post.verified)&&<ShieldCheck size={12}/>}</div><Link to={base} search={{...search,post:post.id}} resetScroll={false}><h2>{post.title}</h2></Link>{post.price!==null&&<p className="lux-card-price">{dollars(post.price)}</p>}<div className="lux-post-creator"><Link to="/store" search={{role:search.role}}><img src={post.images[0]} width={20} height={20} alt=""/><span>{post.creator}</span></Link><Button variant="ghost" className={`lux-heart ${preview.saved.includes(post.id)?'active':''}`} aria-label={`Save ${post.title}`} aria-pressed={preview.saved.includes(post.id)} onClick={()=>preview.toggleSaved(post.id)}><Heart/>{post.likes+(preview.saved.includes(post.id)?1:0)}</Button></div></div>
 </article>)}</div>)}</div>:<div className="lux-empty"><Compass/><h2>No finds here yet.</h2><p>Follow a studio or choose another category.</p><Button asChild variant="goldOutline"><Link to="/store">Explore VS Watch Studio<ArrowRight/></Link></Button></div>;
}
function ProductDetail({post,user,requestAuth,close,onPanel,notify}:{post:LuxuryPost;user:AuthUser|null;requestAuth:()=>void;close:()=>void;onPanel:(panel:'chat'|'cart'|'checkout')=>void;notify:(s:string)=>void}) {
 const preview=useMarketPreview(),reduced=useReducedMotion();const carousel=useRef<HTMLDivElement>(null);const [slide,setSlide]=useState(0);
 const verified=preview.audits[post.id]?preview.audits[post.id]==='Approved':post.verified;
 return <Dialog.Root open onOpenChange={open=>{if(!open)close();}}><Dialog.Portal><Dialog.Overlay asChild><motion.div className="lux-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/></Dialog.Overlay><Dialog.Content asChild aria-describedby={undefined}><motion.div className="lux-detail" initial={{y:reduced?0:'100%'}} animate={{y:0}} exit={{y:reduced?0:'100%'}} transition={{type:'spring',damping:32,stiffness:300}}>
 <div className="lux-detail-top"><Button variant="ghost" size="icon" aria-label="Close product" onClick={close}><ArrowLeft/></Button><Link to="/store" className="detail-seller"><img src={post.images[0]} width={32} height={32} alt=""/><span>{post.creator}<small>Watchmaker & curator</small></span></Link><Button variant="goldOutline" size="sm" onClick={preview.follow}>{preview.following?<Check size={12}/>:<Plus size={12}/>}<span>{preview.following?'Following':'Follow'}</span></Button><Button variant="ghost" size="icon" aria-label="Share product" onClick={async()=>{try{if(navigator.share)await navigator.share({title:post.title,url:window.location.href});else{await navigator.clipboard.writeText(window.location.href);notify('Product link copied');}}catch{/* cancelled */}}}><Share2/></Button></div>
 <div className="lux-detail-scroll"><div className="lux-carousel-wrap"><div className="lux-carousel" ref={carousel} onScroll={e=>setSlide(Math.round(e.currentTarget.scrollLeft/e.currentTarget.clientWidth))}>{post.video?<video src={post.video} poster={post.images[0]} controls playsInline preload="metadata"/>:post.images.map((src,i)=><img key={i} src={src} width={512} height={512} alt={`${post.title} · view ${i+1}`}/>)}</div><span className="lux-counter">{slide+1}/{post.video?1:post.images.length}</span>{verified&&<span className="lux-verified"><ShieldCheck size={14}/> VELA VERIFIED</span>}{post.short&&!post.video&&<span className="sample-media-label">Shorts · Still preview</span>}</div>
 {post.images.length>1&&!post.video&&<div className="carousel-controls"><Button size="icon" variant="ghost" aria-label="Previous image" disabled={slide===0} onClick={()=>carousel.current?.scrollBy({left:-(carousel.current.clientWidth),behavior:reduced?'auto':'smooth'})}><ArrowLeft/></Button>{post.images.map((_,i)=><span key={i} className={`carousel-dot ${slide===i?'active':''}`}/>)}<Button size="icon" variant="ghost" aria-label="Next image" disabled={slide===post.images.length-1} onClick={()=>carousel.current?.scrollBy({left:carousel.current.clientWidth,behavior:reduced?'auto':'smooth'})}><ArrowRight/></Button></div>}
 <div className="lux-detail-copy"><div className="flex flex-wrap items-center justify-between gap-3">{post.price!==null&&<p className="lux-price">{dollars(post.price)}</p>}<span className="text-xs text-muted-foreground"><Eye size={13} className="mr-1 inline"/>{post.views} views</span></div><Dialog.Title className="mt-4 text-xl font-semibold leading-relaxed">{post.title}</Dialog.Title><div className="detail-tags"><span>{post.factory}</span><span>{post.category}</span>{post.sample&&<span>Studio sample</span>}</div><p className="mt-5 text-sm leading-7 text-muted-foreground">{post.description}</p><dl className="lux-specs"><div><dt>Specification</dt><dd>1:1 studio specification</dd></div><div><dt>Case & bracelet</dt><dd>Stainless steel</dd></div><div><dt>Crystal</dt><dd>Sapphire</dd></div><div><dt>Movement</dt><dd>Automatic mechanical</dd></div></dl><p className="mt-5 text-xs leading-6 text-primary">#WatchCommunity #Automatic #{post.factory.replaceAll(' ','')} #VelaFinds</p><div className="mt-7 border-t border-border pt-5"><h3 className="text-sm font-medium">Studio notes</h3><p className="mt-2 text-xs leading-6 text-muted-foreground">{post.sample?'Sample product, pricing and verification. No brand affiliation or real inspection claim.':'Contact the studio to confirm specifications and availability.'}</p></div><ProductComments postId={post.id} user={user} requestAuth={requestAuth}/></div></div>
 <div className="lux-detail-actions"><Button variant="ghost" size="icon" aria-label="Chat with seller" onClick={()=>onPanel('chat')}><MessageCircle/></Button><Button variant="ghost" size="icon" aria-label="Save product" aria-pressed={preview.saved.includes(post.id)} className={preview.saved.includes(post.id)?'text-primary':''} onClick={()=>preview.toggleSaved(post.id)}><Bookmark fill={preview.saved.includes(post.id)?'currentColor':'none'}/></Button><Button variant="goldOutline" onClick={()=>{preview.addCart(post);notify('Added to your sample shopping bag');}}>Add to Cart</Button><Button variant="gold" onClick={()=>onPanel('checkout')}>Buy Now<ArrowRight size={14}/></Button></div>
 </motion.div></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
export function Overlay({title,close,children,side=false}:{title:string;close:()=>void;children:React.ReactNode;side?:boolean}) {
 return <Dialog.Root open onOpenChange={open=>{if(!open)close();}}><Dialog.Portal><Dialog.Overlay className="lux-backdrop overlay-front"/><Dialog.Content className={side?'lux-menu':'lux-dialog'} aria-describedby={undefined}><div className="flex items-center justify-between gap-3"><Dialog.Title className="text-xl font-semibold">{title}</Dialog.Title><Button variant="ghost" size="icon" aria-label="Close dialog" onClick={close}><X/></Button></div>{children}</Dialog.Content></Dialog.Portal></Dialog.Root>;
}
function CommercePanel({panel,selected,close,onPanel,notify}:{panel:string;selected:LuxuryPost|undefined;close:()=>void;onPanel:(panel:'checkout')=>void;notify:(s:string)=>void}) {
 const preview=useMarketPreview();const [sent,setSent]=useState(false),[message,setMessage]=useState(''),[messages,setMessages]=useState<string[]>([]);
 const item=selected || preview.cart[0];
 return <Overlay title={({chat:'Chat with studio',cart:'Your shopping bag',checkout:'Order preview',settings:'Profile settings',apply:'Become a Vela seller',orders:'Order history'} as Record<string,string>)[panel] || 'My Vela'} close={close}>
 {panel==='chat'?<><p className="sample-notice">Sample conversation · Messages are not delivered</p><div className="chat-bubble">VS Watch Studio: Hello. Which details would you like to see?</div>{messages.map((m,i)=><div className="chat-bubble outgoing" key={i}>{m}</div>)}<form className="mt-6 flex gap-2" onSubmit={e=>{e.preventDefault();if(message.trim()){setMessages(p=>[...p,message.trim()]);setMessage('');}}}><input className="form-input" aria-label="Message to seller" value={message} onChange={e=>setMessage(e.target.value)} placeholder="Ask about the watch…"/><Button type="submit" variant="gold" size="icon" aria-label="Send sample message"><ArrowRight/></Button></form></>:
 panel==='cart'?<><p className="sample-notice">Sample shopping bag · No payment taken</p>{preview.cart.length?preview.cart.map(p=><div key={p.id} className="cart-line"><img src={p.images[0]} width={64} height={64} alt=""/><div><p className="text-sm">{p.title}</p><span className="text-sm text-primary">{dollars(p.price ?? 0)}</span></div><Button size="icon" variant="ghost" aria-label={`Remove ${p.title}`} onClick={()=>preview.removeCart(p.id)}><X/></Button></div>):<p className="py-10 text-center text-muted-foreground">Your bag is empty.</p>}{preview.cart.length>0&&<div className="mt-5 flex items-center justify-between gap-3"><span className="font-semibold">Total {dollars(preview.cart.reduce((a,p)=>a+(p.price ?? 0),0))}</span><Button variant="gold" onClick={()=>onPanel('checkout')}>Review order<ArrowRight/></Button></div>}</>:
 panel==='checkout'?sent?<div className="py-8 text-center"><Check className="mx-auto mb-4 text-primary" size={36}/><h2 className="text-lg font-semibold">Sample order created</h2><p className="mt-3 text-sm text-muted-foreground">Awaiting payment. No charge has been made.</p><Button asChild variant="goldOutline" className="mt-6"><Link to="/me" search={{panel:'orders'}}>View orders</Link></Button></div>:<><p className="sample-notice">Preview checkout · Payment is not connected</p>{item?<form onSubmit={e=>{e.preventDefault();preview.order(item);setSent(true);}}><div className="cart-line"><img src={item.images[0]} width={64} height={64} alt=""/><div><p>{item.title}</p><p className="mt-2 text-primary">{dollars(item.price ?? 0)}</p></div></div><label className="form-label" htmlFor="checkout-name">Recipient name</label><input id="checkout-name" className="form-input" required autoComplete="name"/><label className="form-label" htmlFor="checkout-address">Shipping address</label><textarea id="checkout-address" className="form-input" required autoComplete="street-address"/><label className="form-label" htmlFor="checkout-region">Destination</label><select id="checkout-region" className="form-input"><option>Mainland China</option><option>South Korea</option><option>Global</option></select><p className="my-5 text-xs leading-6 text-muted-foreground">Shipping and taxes require a studio quote. This form creates a sample order only.</p><Button variant="gold" className="w-full" type="submit">Create sample order<ArrowRight/></Button></form>:<p className="py-8 text-muted-foreground">Add a product to your bag first.</p>}</>:
 panel==='apply'?preview.application?<div className="py-8 text-center"><ShieldCheck className="mx-auto mb-4 text-primary"/><h2>Sample application received</h2><p className="mt-3 text-sm text-muted-foreground">Pending review in the admin preview.</p></div>:<form className="mt-5" onSubmit={e=>{e.preventDefault();preview.apply();}}><p className="sample-notice">Seller application preview · Do not upload real ID documents</p><label className="form-label" htmlFor="studio-name">Studio name</label><input id="studio-name" className="form-input" required/><label className="form-label" htmlFor="studio-region">Business region</label><input id="studio-region" className="form-input" required/><label className="form-label" htmlFor="studio-bio">About your studio</label><textarea id="studio-bio" className="form-input" required/><label className="mt-4 flex gap-2 text-xs leading-6"><input type="checkbox" required/>I understand this is a sample KYC application.</label><Button variant="gold" className="mt-6 w-full">Submit sample application</Button></form>:
 panel==='orders'?<><p className="sample-notice">Sample orders</p>{preview.orders.length?preview.orders.map(o=><div className="order-row" key={o.id}><div><span className="lux-eyebrow">{o.id}</span><p className="mt-2 text-sm">{o.title}</p><p className="mt-2 text-xs text-primary">{preview.audits[o.id] || o.status}</p></div><strong>{dollars(o.amount)}</strong></div>):<p className="py-10 text-center text-muted-foreground">No orders yet.</p>}</>:
 <form className="mt-5" onSubmit={e=>{e.preventDefault();const fields=new FormData(e.currentTarget);preview.saveProfile(String(fields.get('displayName') || 'Vela Member'),String(fields.get('region') || 'Global'));notify('Sample profile updated for this preview');close();}}><p className="sample-notice">Sample profile settings</p><label className="form-label" htmlFor="profile-name">Display name</label><input id="profile-name" name="displayName" className="form-input" defaultValue={preview.profile.name} required/><label className="form-label" htmlFor="profile-region">Region</label><select id="profile-region" name="region" className="form-input" defaultValue={preview.profile.region}><option>Global</option><option>Mainland China</option><option>South Korea</option></select><Button variant="gold" className="mt-6 w-full" type="submit">Save profile</Button></form>}
 </Overlay>;
}
function StoreHeader({tab,role}:{tab:string;role:'buyer'|'seller'|'admin'|undefined}) {
 const p=useMarketPreview();return <><div className="store-banner"><img src={watchImages[5]} width={512} height={512} alt="Studio watch on the inspection bench"/><span>THE ART OF<br/><strong>EVERY SECOND.</strong></span><small>VS WATCH STUDIO</small></div><div className="store-profile"><img className="store-avatar" src={watchImages[0]} width={90} height={90} alt="VS Watch Studio"/><div className="store-title"><div><h1>VS Watch Studio <ShieldCheck size={20}/></h1><span className="text-xs text-primary">Verified seller · Sample studio</span></div><Button variant="goldOutline" onClick={p.follow}>{p.following?<Check/>:<Plus/>}{p.following?'Following':'Follow'}</Button></div><p className="store-bio">Independent watch curation. Thoughtful details, precise movements.<br/>From our workbench to your everyday.</p><div className="store-stats"><span><strong>{p.following?'12.9K':'12.8K'}</strong> Followers</span><span><strong>12</strong> Products</span><span><strong>4.9</strong> Rating</span></div></div><nav className="lux-tabs store-tabs">{['products','shorts','reviews'].map(t=><Button asChild variant="ghost" className={`lux-tab ${tab===t?'active':''}`} key={t}><Link to="/store" search={{role,storeTab:t as 'products'|'shorts'|'reviews'}}>{t[0]?.toUpperCase()}{t.slice(1)}</Link></Button>)}</nav></>;
}
function Reviews(){return <div className="review-list">{[['A. Chen','Beautiful finishing. The studio shared detailed photos before shipping.'],['J. Park','Quick communication and a carefully packed watch.'],['M. Lee','The dial looks even better in person.']].map(([name,text])=><article key={name}><div className="flex justify-between"><strong>{name}</strong><span className="text-primary">★★★★★</span></div><p className="mt-3 text-sm leading-7 text-muted-foreground">{text}</p><span className="mt-3 block text-xs text-muted-foreground">Sample review · Verified purchase preview</span></article>)}</div>;}
