import { Link } from '@tanstack/react-router';
import { ArrowLeft } from 'lucide-react';
import { Button } from './ui/button';
import { LiveOrderBoard } from './live-orders';
import type { User } from '@supabase/supabase-js';
export function MarketHelp({kind,user,requestAuth}:{kind:'escrow'|'support'|'privacy';user:User|null;requestAuth:()=>void}) {
 return <article className="mx-auto max-w-2xl py-8"><Button asChild variant="ghost" className="mb-5"><Link to="/"><ArrowLeft/>VELA</Link></Button><h1 className="mb-6 text-2xl font-semibold">{kind==='escrow'?'가상화폐 에스크로 이용 안내':kind==='support'?'1:1 지원 · 분쟁 센터':'개인정보 보호 · SHA-256'}</h1>
 {kind==='escrow'?<div className="space-y-6 text-sm leading-7"><ol className="list-decimal space-y-4 pl-5"><li>USDT(TRC-20/ERC-20), BTC 또는 ETH 네트워크를 선택하고, 수신 주소와 금액을 확인합니다.</li><li>전송 후 TXID를 제출합니다. 관리자의 결제 확인 전에는 입금 완료로 간주하지 않습니다.</li><li>판매자는 검수 후 최소 9장의 디테일 사진과 1개의 영상을 주문 QC 게시판에 올립니다.</li><li>구매자는 검수 자료를 확인하고 추가 사진을 요청하거나 QC를 승인합니다.</li><li>발송 후 판매자가 송장번호를 등록합니다. 주문 게시판에서 배송 상태와 17TRACK 조회 링크를 확인합니다.</li><li>수령 후 구매자가 수령 확인과 리뷰를 진행합니다. 문제가 있으면 주문에서 분쟁을 열 수 있습니다.</li></ol><p className="border-t border-border pt-4 text-muted-foreground">현재 자동 입금 검증·가상화폐 정산은 미연결이며, 실제 운영 지갑 확인이 필요합니다. 자동 배송 추적도 서비스 연결 전까지 17TRACK 조회 링크를 이용합니다.</p><Button asChild variant="goldOutline"><Link to="/me" search={{panel:'orders'}}>내 주문 · 에스크로 상태</Link></Button></div>:
 kind==='support'?<><p className="mb-6 text-sm leading-7 text-muted-foreground">주문별 판매자 메시지로 문의하거나 분쟁을 열 수 있습니다. 분쟁 접수 시 구매자·판매자·관리자가 같은 주문 대화에 참여합니다. 주문이 없는 일반 상담은 아직 연결되지 않았습니다.</p>{user?<LiveOrderBoard as="buyer"/>:<Button variant="goldOutline" onClick={requestAuth}>로그인하고 내 주문 확인</Button>}</>:
 <div className="space-y-6 text-sm leading-7"><section><h2 className="font-semibold text-primary">전화번호와 계정 식별</h2><p>가입·로그인에 입력한 전화번호는 서버에서 비밀값을 결합한 SHA-256 단방향 해시로 변환됩니다. 계정 식별에는 원문 전화번호 대신 해시를 사용합니다. SHA-256은 전화번호 식별에 적용되며, 비밀번호를 같은 방식으로 저장한다는 뜻은 아닙니다.</p></section><section><h2 className="font-semibold text-primary">익명 프로필</h2><p>계정에는 익명 시스템 ID와 직접 설정한 닉네임을 사용합니다. 판매자 신청과 승인 화면은 시스템 ID·닉네임을 기준으로 처리합니다.</p></section><section><h2 className="font-semibold text-primary">사진·주문·대화</h2><p>프로필 사진과 QC 자료는 비공개 저장 공간에 보관됩니다. QC 자료와 주문 대화는 해당 주문의 구매자·판매자에게만 열리며, 분쟁 시 관리자가 참여할 수 있습니다.</p></section><section><h2 className="font-semibold text-primary">배송 정보와 기기 설정</h2><p>배송용 연락처·주소는 계정 식별용 전화번호 해시와 별개의 정보입니다. 현재 미리보기 배송 프로필, 팔로우 목록, 표시 통화와 언어는 이 기기에 저장됩니다. 전화번호 해시만으로 모든 배송 정보가 익명화되지는 않습니다.</p></section><p className="border-t border-border pt-4 text-muted-foreground">이 페이지는 현재 개인정보 처리 방식에 대한 안내입니다. 법적 운영 정책의 보관기간·삭제 요청 창구·운영자 정보는 확정 전입니다.</p></div>}
 </article>;
}
