import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useServerFn } from '@tanstack/react-start';
import { MessageCircle, Send, UserRound } from 'lucide-react';
import type { User } from '@supabase/supabase-js';
import { Button } from '@/components/ui/button';
import { addComment, getComments } from '@/lib/market.functions';
import { Avatar, AvatarImage, AvatarFallback } from './ui/avatar';
import { timeAgo } from '@/lib/i18n';
export function ProductComments({postId,user,requestAuth,composerOnly=false,qna=false,composerFirst=false,live=false,replyable=false}:{postId:string;user:User|null;requestAuth:()=>void;composerOnly?:boolean;qna?:boolean;composerFirst?:boolean;live?:boolean;replyable?:boolean}) {
 const read=useServerFn(getComments),write=useServerFn(addComment),client=useQueryClient();
 const {data:comments,error,isPending}=useQuery({queryKey:['comments',postId,user?.id ?? 'public'],queryFn:()=>read({data:{postId}}),refetchInterval:!composerOnly||live?5000:false});
 const [replyTo,setReplyTo]=useState<string|null>(null),[reply,setReply]=useState(''),[body,setBody]=useState(''),[pending,setPending]=useState(false),[message,setMessage]=useState('');
 type C=NonNullable<typeof comments>[number];
 const item=(comment:C,isReply=false)=><article className={isReply?'mt-3 flex items-start gap-2':'mt-4 flex items-start gap-3'} aria-label={isReply?'답글':'댓글 항목'}><Avatar className={isReply?'h-7 w-7':'h-9 w-9'}><AvatarImage src={comment.avatar_url ?? undefined} alt={`${comment.nickname} 프로필 사진`} className="object-cover"/><AvatarFallback aria-label="기본 프로필 사진"><UserRound size={16} className="text-muted-foreground"/></AvatarFallback></Avatar><div className="min-w-0 flex-1"><div className="flex flex-wrap items-baseline gap-x-2 gap-y-1 text-xs"><strong className="break-words text-foreground" data-no-translate>{comment.nickname}</strong><time className="text-muted-foreground" dateTime={comment.created_at}>{timeAgo(comment.created_at)}</time></div><p className="mt-1 whitespace-pre-wrap break-words text-sm text-muted-foreground" data-no-translate>{comment.body}</p></div></article>;
const discussion=<><h3 className="flex items-center gap-2 text-sm"><MessageCircle size={15}/>{qna?'상품 Q&A':'댓글'} · {comments?.length || 0}</h3>{error?<p className="mt-4 text-xs text-destructive">댓글을 불러오지 못했습니다.</p>:isPending?<p className="mt-4 text-xs text-muted-foreground">댓글 불러오는 중…</p>:comments?.length?comments.filter(c=>!c.parent_id).map(comment=><div key={comment.id}>{item(comment)}<div className="ml-12">{comments.filter(r=>r.parent_id===comment.id).map(r=><div key={r.id}>{item(r,true)}</div>)}{replyable&&(replyTo===comment.id?<form className="mt-2 flex gap-2" onSubmit={async e=>{e.preventDefault();if(!reply.trim()||pending)return;setPending(true);setMessage('');try{await write({data:{postId,body:reply,parentId:comment.id}});setReply('');setReplyTo(null);await client.invalidateQueries({queryKey:['comments',postId]});}catch{setMessage('답글을 저장하지 못했습니다.');}finally{setPending(false);}}}><input autoFocus aria-label="답글 입력" placeholder="답글을 입력하세요…" className="form-input min-w-0" value={reply} onChange={e=>setReply(e.target.value)} maxLength={1000}/><Button type="submit" variant="gold" size="icon" aria-label="답글 등록" disabled={pending}><Send/></Button></form>:<button type="button" className="mt-1 text-xs text-primary" onClick={()=>{if(!user){requestAuth();return;}setReplyTo(comment.id);setReply('');}}>답글 달기</button>)}</div></div>):<p className="mt-4 text-xs text-muted-foreground">아직 댓글이 없습니다.</p>}</>;
 const composer=<form className={composerOnly?"shorts-comment-form":"mt-5 flex gap-2"} onSubmit={async e=>{e.preventDefault();if(!user){requestAuth();return;}if(!body.trim()||pending)return;setPending(true);setMessage('');try{await write({data:{postId,body}});setBody('');await client.invalidateQueries({queryKey:['comments',postId]});}catch{setMessage('댓글을 저장하지 못했습니다. 다시 시도해 주세요.');}finally{setPending(false);}}}><input aria-label={qna?'상품 질문 입력':composerOnly?'숏폼 댓글 입력':'댓글 입력'} placeholder={qna?'상품에 대해 질문해 주세요…':'댓글 남기기…'} className="form-input min-w-0" value={body} onChange={e=>setBody(e.target.value)} maxLength={1000}/><Button type="submit" variant="gold" size="icon" aria-label={qna?'질문 등록':'댓글 보내기'} disabled={pending}><Send/></Button></form>;
 return <section className={composerOnly?'shorts-comment-composer':composerFirst?'shorts-live-comments':'mt-6 border-t border-border pt-5'}>{composerFirst||composerOnly?composer:null}{!composerOnly&&discussion}{!composerFirst&&!composerOnly?composer:null}{message&&<p role="alert" className="mt-3 text-xs text-destructive">{message}</p>}</section>;
}
