import { useEffect, useState } from 'react';
import { Link, useNavigate, useRouterState } from '@tanstack/react-router';
import type { User } from '@supabase/supabase-js';
import { AlertTriangle, BadgeCheck, Pencil, X, Wallet, ShieldCheck, ChevronRight, Star, PackageCheck } from 'lucide-react';
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip } from 'recharts';
import * as Dialog from '@radix-ui/react-dialog';
import { Button } from './ui/button';
import { useMyAccount } from './seller-account';
import { StudioTierBadge } from './reputation';
import { StudioTierDetails, StudioReviews } from './studio-details';
import { SellerReplacementCenter } from './seller-replacement-center';
import { SellerEscrowWallet } from './seller-wallet';
import { useAvatarUrl } from '@/lib/avatar';
import { useStudioReputation } from '@/lib/studio-tier';
import { useSellerWorkflows } from '@/lib/use-seller-workflows';
import { completedOrders, salesTrend, type SalesPeriod } from '@/lib/seller-workflows';
import { ratingAverage, ratingDowngradeAlert, sellerTier, studioNames, tierRules } from '@/lib/reputation';
import { marketSearch } from '@/lib/market';
import { formatMoney } from '@/lib/currency';

export function SellerStudio({ user }: { user: User }) {
  const search = marketSearch.parse(useRouterState({ select: s => s.location.search })), navigate = useNavigate();
  const account = useMyAccount(user), isSeller = !!account.data?.roles.includes('seller'), avatar = useAvatarUrl(account.data?.profile?.avatar_url);
  const performance = useStudioReputation(isSeller ? user.id : null), workflows = useSellerWorkflows(user.id);
  const reputation = performance.data?.reputation, tier = reputation ? sellerTier(reputation) ?? 'standard' : 'standard', average = reputation ? ratingAverage(reputation) : null, alert = reputation ? ratingDowngradeAlert(reputation) : null;
  const [today, setToday] = useState(''); useEffect(() => setToday(new Date().toISOString().slice(0, 10)), []);
  const period: SalesPeriod = search.salesPeriod ?? 'daily', trend = today ? salesTrend(workflows.data?.orders ?? [], period, search.salesDate ?? today) : [], done = completedOrders(workflows.data?.orders ?? []), total = trend.reduce((s, b) => s + b.total, 0);
  const tab = search.studioTab ?? 'tier';
  const reviewContent = <StudioReviews stats={performance.data?.stats} recent={performance.data?.recent} error={performance.isError}/>;
  return <div className="seller-studio studio-compact" lang="ko" data-no-translate>
    <header><div className="studio-title-row"><h1>내 스튜디오</h1><Button asChild variant="goldOutline" size="sm"><Link to="/seller" search={prev => ({ ...prev, panel: 'settings' })} resetScroll={false}><Pencil className="size-4"/>프로필 편집</Link></Button></div>
      <div className="studio-identity"><div className="studio-avatar">{avatar ? <img src={avatar} alt="스튜디오 프로필"/> : <span>V</span>}</div><div className="min-w-0"><div className="studio-name-line"><h2>{account.data?.profile?.nickname ?? 'VELA 스튜디오'}</h2></div><p className="studio-system-id">VELA ID · {account.data?.profile?.system_code ?? '—'}</p><div className="studio-credentials"><span className="studio-account-label"><BadgeCheck size={13}/>{isSeller ? '승인된 셀러' : '관리자'}</span>{isSeller && <span className="studio-active-tier"><StudioTierBadge tier={tier}/><span>스튜디오 · 수수료 {tierRules[tier].fee}%</span></span>}</div></div></div>
      <div className="studio-kpis"><div className="studio-kpi"><span>누적 매출 ($)</span><strong>{reputation ? formatMoney(reputation.volumeUsd ?? 0, 'USD') : '—'}</strong></div><Button asChild variant="ghost" className="studio-kpi"><Link to="/seller" search={prev => ({ ...prev, studioDialog: 'reviews' })} resetScroll={false}><span>평균 평점 <ChevronRight/></span><strong><Star className="text-primary"/>{average === null ? '—' : average.toFixed(2)}</strong></Link></Button><Button asChild variant="ghost" className="studio-kpi"><Link to="/seller" search={prev => ({ ...prev, studioDialog: 'history' })} resetScroll={false}><span>완료 주문 <ChevronRight/></span><strong>{workflows.data ? done.length : '—'}<small>건</small></strong></Link></Button></div>
    </header>
    <section className="studio-settlement" aria-label="에스크로 정산"><div className="studio-escrow-metric studio-escrow-released"><div className="flex items-center gap-2 text-sm"><Wallet className="size-4 text-primary"/><h2>입금 완료 총액</h2></div><strong>{workflows.data ? formatMoney(workflows.data.escrow.released, 'USD') : '—'}</strong><p>에스크로 해제 누적액 · USD 환산</p><Button asChild variant="goldOutline" size="sm"><Link to="/seller" search={prev => ({ ...prev, studioDialog: 'wallet' })} resetScroll={false}><Wallet className="size-4"/>지갑 / 출금</Link></Button></div><div className="studio-escrow-metric"><div className="flex items-center gap-2 text-sm"><ShieldCheck className="size-4 text-primary"/><h2>입금 대기 총액</h2></div><strong>{workflows.data ? formatMoney(workflows.data.escrow.pending, 'USD') : '—'}</strong><p>배송 및 구매 확정까지 보관 중</p></div></section>
    {workflows.isError && <p role="alert" className="text-sm text-destructive">매출·정산 정보를 불러오지 못했습니다.</p>}
    <section className="studio-analytics" aria-label="매출 분석"><div className="studio-analytics-heading"><h2>매출 분석</h2><div role="group" aria-label="매출 기간" className="studio-periods">{([['daily', '일별'], ['monthly', '월별'], ['yearly', '연별']] as const).map(([id, label]) => <Button asChild key={id} size="sm" variant={period === id ? 'goldOutline' : 'ghost'}><Link to="/seller" search={prev => ({ ...prev, salesPeriod: id })} resetScroll={false}>{label}</Link></Button>)}</div></div><div className="flex items-center justify-between gap-3"><strong className="seller-sales-total">{workflows.data ? formatMoney(total, 'USD') : '—'}</strong><input type="date" aria-label="매출 기준일" className="form-input studio-date" value={search.salesDate ?? today} onChange={e => { if (e.target.value) void navigate({ to: '/seller', search: prev => ({ ...prev, salesDate: e.target.value }), resetScroll: false }); }}/></div><div className="seller-sales-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={trend} margin={{ top: 10, right: 8, left: 0, bottom: 0 }}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="label" minTickGap={35} stroke="var(--muted-foreground)" fontSize={11}/><YAxis width={48} stroke="var(--muted-foreground)" fontSize={11}/><Tooltip formatter={(value: number) => [formatMoney(value, 'USD'), '매출']}/><Line type="monotone" dataKey="total" stroke="var(--primary)" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></div></section>
    <div className="studio-detail-tabs" role="tablist" aria-label="스튜디오 상세">{([['tier', '스튜디오 등급 현황'], ['replacement', '초기불량/교환 센터'], ['reviews', '고객 리뷰']] as const).map(([id, label]) => <Button asChild variant="ghost" key={id}><Link to="/seller" role="tab" id={`studio-tab-${id}`} aria-selected={tab === id} aria-controls="studio-detail-panel" tabIndex={tab === id ? 0 : -1} onKeyDown={e => { if (!['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(e.key)) return; e.preventDefault(); const ids = ['tier', 'replacement', 'reviews'] as const, index = ids.indexOf(id), target = ids[e.key === 'Home' ? 0 : e.key === 'End' ? 2 : (index + (e.key === 'ArrowRight' ? 1 : 2)) % 3]; if (target) { void navigate({ to: '/seller', search: prev => ({ ...prev, studioTab: target }), resetScroll: false }); document.getElementById(`studio-tab-${target}`)?.focus(); } }} search={prev => ({ ...prev, studioTab: id })} resetScroll={false}>{label}</Link></Button>)}</div>
    <section className="studio-detail-panel" id="studio-detail-panel" role="tabpanel" aria-labelledby={`studio-tab-${tab}`}>
      {tab === 'tier' ? <>{alert && <div role="alert" className="studio-rating-alert"><AlertTriangle size={18}/><p>평점 {alert.average.toFixed(2)}점 · {studioNames[alert.tier]} 기준 미달로 {studioNames[alert.fallback]} 적용 중</p></div>}{performance.isError ? <p role="alert">등급 정보를 불러오지 못했습니다.</p> : reputation ? <StudioTierDetails reputation={reputation}/> : <p className="seller-empty">{isSeller ? '등급 정보를 불러오는 중…' : '등급과 리뷰는 승인된 셀러 계정에서 확인할 수 있습니다.'}</p>}</> : tab === 'replacement' ? <SellerReplacementCenter user={user}/> : isSeller ? reviewContent : <p className="seller-empty">고객 리뷰는 승인된 셀러 계정에서 확인할 수 있습니다.</p>}
    </section>
    {search.studioDialog && <Dialog.Root open onOpenChange={open => { if (!open) { if (window.history.state?.__TSR_index > 0) window.history.back(); else void navigate({ to: '/seller', search: prev => ({ ...prev, studioDialog: undefined }), replace: true, resetScroll: false }); } }}><Dialog.Portal><Dialog.Overlay className="lux-backdrop overlay-front"/><Dialog.Content className="lux-dialog" aria-describedby={undefined} lang="ko" data-no-translate><div className="flex items-center justify-between"><Dialog.Title className="text-lg font-semibold">{search.studioDialog === 'reviews' ? '구매 고객 리뷰' : search.studioDialog === 'wallet' ? '에스크로 지갑 · 출금' : '판매 내역 · 완료 주문'}</Dialog.Title><Dialog.Close asChild><Button variant="ghost" size="icon" aria-label="닫기"><X/></Button></Dialog.Close></div>{search.studioDialog === 'wallet' ? <><p className="mt-4 text-sm text-muted-foreground">입금 완료 총액은 누적 정산액이며 현재 출금 가능 잔액이 아닙니다. 암호화폐 출금 기능은 아직 연결되지 않았습니다.</p><SellerEscrowWallet user={user}/></> : search.studioDialog === 'reviews' ? isSeller ? reviewContent : <p className="seller-empty">셀러 계정에서 고객 리뷰를 확인할 수 있습니다.</p> : workflows.isError ? <p role="alert" className="seller-empty">판매 내역을 불러오지 못했습니다.</p> : !workflows.data ? <p className="seller-empty">판매 내역을 불러오는 중…</p> : done.length ? done.map(o => <div className="seller-thread-row" key={o.id}><div><strong>{o.title}</strong><small>{o.order_no} · {new Date(o.updated_at).toLocaleDateString('ko-KR')}</small></div><strong>{formatMoney(o.amount_usd, 'USD')}</strong></div>) : <p className="seller-empty"><PackageCheck className="mx-auto mb-2 size-5"/>완료된 주문이 없습니다.</p>}</Dialog.Content></Dialog.Portal></Dialog.Root>}
  </div>;
}
