/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as EscrowGuideRouteImport } from './routes/escrow-guide'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as MarketRouteImport } from './routes/market'
import { Route as MeRouteImport } from './routes/me'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SupportRouteImport } from './routes/support'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as ShortsIdRouteImport } from './routes/shorts.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EscrowGuideRoute = EscrowGuideRouteImport.update({
  id: '/escrow-guide',
  path: '/escrow-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortsIdRoute = ShortsIdRouteImport.update({
  id: '/shorts/$id',
  path: '/shorts/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/escrow-guide': typeof EscrowGuideRoute
  '/explore': typeof ExploreRoute
  '/market': typeof MarketRoute
  '/me': typeof MeRoute
  '/privacy': typeof PrivacyRoute
  '/seller': typeof SellerRoute
  '/store': typeof StoreRoute
  '/support': typeof SupportRoute
  '/upload': typeof UploadRoute
  '/shorts/$id': typeof ShortsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/escrow-guide': typeof EscrowGuideRoute
  '/explore': typeof ExploreRoute
  '/market': typeof MarketRoute
  '/me': typeof MeRoute
  '/privacy': typeof PrivacyRoute
  '/seller': typeof SellerRoute
  '/store': typeof StoreRoute
  '/support': typeof SupportRoute
  '/upload': typeof UploadRoute
  '/shorts/$id': typeof ShortsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/escrow-guide': typeof EscrowGuideRoute
  '/explore': typeof ExploreRoute
  '/market': typeof MarketRoute
  '/me': typeof MeRoute
  '/privacy': typeof PrivacyRoute
  '/seller': typeof SellerRoute
  '/store': typeof StoreRoute
  '/support': typeof SupportRoute
  '/upload': typeof UploadRoute
  '/shorts/$id': typeof ShortsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/escrow-guide'
    | '/explore'
    | '/market'
    | '/me'
    | '/privacy'
    | '/seller'
    | '/store'
    | '/support'
    | '/upload'
    | '/shorts/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/escrow-guide'
    | '/explore'
    | '/market'
    | '/me'
    | '/privacy'
    | '/seller'
    | '/store'
    | '/support'
    | '/upload'
    | '/shorts/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/escrow-guide'
    | '/explore'
    | '/market'
    | '/me'
    | '/privacy'
    | '/seller'
    | '/store'
    | '/support'
    | '/upload'
    | '/shorts/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  EscrowGuideRoute: typeof EscrowGuideRoute
  ExploreRoute: typeof ExploreRoute
  MarketRoute: typeof MarketRoute
  MeRoute: typeof MeRoute
  PrivacyRoute: typeof PrivacyRoute
  SellerRoute: typeof SellerRoute
  StoreRoute: typeof StoreRoute
  SupportRoute: typeof SupportRoute
  UploadRoute: typeof UploadRoute
  ShortsIdRoute: typeof ShortsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escrow-guide': {
      id: '/escrow-guide'
      path: '/escrow-guide'
      fullPath: '/escrow-guide'
      preLoaderRoute: typeof EscrowGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorts/$id': {
      id: '/shorts/$id'
      path: '/shorts/$id'
      fullPath: '/shorts/$id'
      preLoaderRoute: typeof ShortsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  EscrowGuideRoute: EscrowGuideRoute,
  ExploreRoute: ExploreRoute,
  MarketRoute: MarketRoute,
  MeRoute: MeRoute,
  PrivacyRoute: PrivacyRoute,
  SellerRoute: SellerRoute,
  StoreRoute: StoreRoute,
  SupportRoute: SupportRoute,
  UploadRoute: UploadRoute,
  ShortsIdRoute: ShortsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
